name: buckrate_calculator
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: ^0.19.0
  url_launcher: ^6.2.3
  url_strategy: ^0.2.0
  animated_text_kit: ^4.2.2
  place_picker:
    path: ./place_picker


dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
